Auction/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^main/',include('BuyandSell.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

BuyandSell/urls.py
from django.conf.urls import url
from django.contrib import admin
from .import views

app_name ='BuyandSell'

urlpatterns = [
    url(r'^Buy/$', views.home,name='main'),
    url(r'^login_user/$', views.login_user,name='login_user'),
    url(r'^signUp/$', views.signUp,name='signUp'),
    url(r'^items/$', views.items,name='items'),
    url(r'^logout/$', views.logOut,name='logout'),
    url(r'^about/$', views.about,name='About'),
    url(r'^(?P<username>[\w-]+)/deleteme/$', views.deleteme,name='deleteme'),
    url(r'^sell/$', views.sell,name='sell'),
    url(r'^(?P<username>[\w-]+)/profile/$', views.profile,name='profile'),
    url(r'^(?P<username>[\w-]+)/$', views.test,name='test'),
]


BuyandSell/models.py
from django.db import models
from django.contrib.auth.models import User



class UserProfile(models.Model):
	name = models.CharField(max_length=100,default="ram")
	user = models.OneToOneField(User,on_delete=models.CASCADE,primary_key=True)
	email= models.EmailField()
	contactno=models.CharField(max_length=10)
	image=models.FileField(default='jon.png')
	
	# def __str__(self):
	# 	return self.item_name


class item(models.Model):
	item_name=models.CharField(max_length=100)
	item_id=models.CharField(max_length=50)
	price  = models.CharField(max_length=50)
	username = models.CharField(max_length=50)
	description =models.CharField(max_length=100)
	image=models.FileField()
	available =models.BooleanField(default=False)
	report=models.FileField(null=True)





BuyandSell/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import item,UserProfile


class SellForm(forms.ModelForm):

    class Meta:
        model = Album
        fields = ['artist', 'album_title', 'genre', 'album_logo']

BuyandSell/views.py
from django.shortcuts import render
from django.template.context import RequestContext
from django.http import HttpResponse
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.http import JsonResponse
from django.shortcuts import render, redirect , get_object_or_404
from django.utils import six
from itertools import product,chain
from .models import item,UserProfile
from django.contrib.auth.models import User
from django.core.files.storage import FileSystemStorage


def main(request):
	return HttpResponse('<h1> Bye </h1>')

def home(request):
	return render(request,'BuyandSell/main.html')


def test(request,username):
	print("hi whats up")
	print(UserProfile.user)
	print("Hii This is sourav")
	print(username)
	u = get_object_or_404(User, username=username)
	me=UserProfile.objects.filter(user=u)
	return render(request,'BuyandSell/seller_info.html',{'obj': me})


def login_user(request):
	if not request.user.is_authenticated():
		if request.method == "POST":
			username = request.POST['name']
			password = request.POST['password']
			user = authenticate(username=username , password=password)
			login(request,user)
			if request.user.is_authenticated():
				return redirect('BuyandSell:items')
			else:
				return render(request, 'BuyandSell/login.html', {'error_message': 'Invalid login'})
		else:
			return render(request, 'BuyandSell/login.html', {'error_message': 'Invalid login'})
	else:
		return redirect('BuyandSell:items')

def logOut(request):
	logout(request)
	return redirect('BuyandSell:login_user')


def sell(request):
	if request.method == "POST":
		item_name=request.POST['name']
		item_id=request.POST['id']
		price = request.POST["price"]
		description=request.POST['description']
		image=request.FILES['image']
		report=request.FILES['report']
		obj2=item(item_name = item_name , item_id= item_id ,price=price,description=description,image=image,report=report)
		obj2.save()
	else:
		return render(request, 'BuyandSell/sell_form.html')
	return redirect('BuyandSell:items')


def signUp(request):
	if request.method == "POST":
		name=request.POST['name']
		email=request.POST['email']
		username=request.POST['username']
		password=request.POST['password']
		user = User.objects.create_user(
			username = username,
			password = password,
			email=email
			)
		user.save()
		contactNumber=request.POST['contactno']
		obj2=UserProfile(name=name,user=user,email=email,contactno=contactNumber)
		obj2.save()
	else:
		return render(request,'BuyandSell/signUp.html')
	return redirect('BuyandSell:login_user')


def profile(request,username):
	print("we are in profile now ")
	result =item.objects.filter(username =username)
	u = get_object_or_404(User, username=username)
	me=UserProfile.objects.filter(user=u)
	return render(request,'BuyandSell/profile.html' ,{'obj2':me,'obj' :result}) 

def search(request):
	if request.method==POST:
		item_name = request.POST['data']
		result=item.objects.filter(item_name=item_name)
		return render(request,'BuyandSell/search.html' ,{'obj' :result}) 
		
# from django.contrib.auth.decorators import login_required
# @login_required(login_url='BuyandSell:login_user')
def items(request):
	context = {}
	# context['username'] = request.user.username
	context['items'] = item.objects.all()
	return render(request,'BuyandSell/home.html',context)

def about(request):
	return render(request,'BuyandSell/about.html')

def deleteme(request,username):
	obj = item.objects.get(item_name=username)
	obj.delete()
	return redirect('BuyandSell:items')

BuyandSell/templates/BuyandSell/about.html
<!DOCTYPE html>
<html>
<head>
	<title>About</title>
  <meta name="description" content="The HTML5 Herald">
  <meta name="author" content="SitePoint">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

	<!-- jQuery library -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

	<!-- Latest compiled JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

</head>
<body>
	<div>
		<p> This is a Website mainly aimed for uploading the project complated by student in their final year</p>
	</div>

</body>
</html>

BuyandSell/templates/BuyandSell/home.html
<!doctype html>

<html lang="en">
<head>
  <meta charset="utf-8">
  {%load static%}
  <title>Home Page</title>
  <meta name="description" content="The HTML5 Herald">
  <meta name="author" content="SitePoint">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

	<!-- jQuery library -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

	<!-- Latest compiled JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
	<link rel="stylesheet" href="../../static/BuyandSell/style.css">
</head>

<body>

	<div class="block-container">
		<div class = 'my-header'>
		NIT Warangal Project Hub
		</div>
 	</div> 
 	

	<!-- <div class = "container">
		<form  action ="{% url 'BuyandSell: search'  data % }" role="search"  enctype="multipart/form-data">
			{% csrf_token %}
			<div class = "form-group">
				<label for="search_box" class = "label_class_1">Search</label>
				<input type="search_input" name= "data" class = "form-control" id="search_box" placeholder="Search">
				<button type="search" class = "btn btn-default">Search</button>
			</div>
		</form>
	</div>
 -->	
 	{% for i in items %}
	<div class = "container">
			<div class = "item_temp">
				<div class = "item_image">
					<img src = "{{ i.image.url }}" style="border: solid 1px black;"/>
				</div>
				<h1>Project Title: {{i.item_name}}</h1>
				<p>Project Group Leader: {{i.item_id}}</p>
				  <p>Guide : {{i.price}}</p>
				  <p>Description : {{i.description}}</p>
				  <p> <a href="{{ i.report.url }}" target="_blank" class="btn btn-primary">Download The Report </a>
				  </p>
			
			</div>
	</div>
	{%endfor%}

	<div class = "page-footer">
	</div>

	<div class="foot-div"></div>

</body>

</html>

BuyandSell/templates/BuyandSell/login.html
<!DOCTYPE html>
<html>
<head>
  <title>Project Hub Login</title>
  {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'BuyandSell/style.css' %}" />
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  {% csrf_token %}
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

</head>
<body>
	<div class="fakenavbar">
  <div class="container">
    <h2>NIT Warangal Project Hub </h2>
  </div>
</div>

  <div class="container"> 
    <div class="jumbotron">
      <div class="jumbotron-content">
        <h1>Project Hub</h1>
        <p class="jumbotron-xs-6">Please Login</p>
        <form name="user-info" action="{% url 'BuyandSell:login_user'%}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
          <div class="form-group">
            <label for="name">Username</label>
            <input type="text" name="name" class="form-control" placeholder="Name">
          </div>
          <div class="form-group">
            <label for="password">Password:</label>
            <input type="password" name="password" class="form-control" placeholder="Password">
          </div>
          <input type="submit" value="submit" name="submit
          ">
        </form >
      </div>
      <!--<p class="img-credit">Image Dynamically Provided by <a href="http://lorempixel.com">LoremPixel</a></p>-->
    </div>
    
    <!--<h2>Remaining Content...</h2>-->
  </div>

<div class="fakefooter">
  
</div>
</body>
</html>

BuyandSell/templates/BuyandSell/profile.html
<!doctype html>

<html lang="en">
<head>
  <meta charset="utf-8">
  {%load static%}
  <title>Profile Page</title>
  <meta name="description" content="The HTML5 Herald">
  <meta name="author" content="SitePoint">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link href='https://fonts.googleapis.com/css?family=Roboto:100,400,300,500,700' rel='stylesheet' type='text/css'>

	<!-- jQuery library -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

	<!-- Latest compiled JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
	<link rel="stylesheet" href = "{% static 'BuyandSell/style.css' %}">
</head>

<body>

	<div class = "my-container">
		<div class = "style_prevu_kit card-container">
				{% for i in obj2 %}
				<img src = "{{i.image.url}}" class ="card-img" />
				<div class = "card-details">
					Name : &nbsp; {{i.name}}
				</div>
				<div class = "card-details">
					Contact No. : &nbsp; {{i.contactno}}
				</div>
				<div class = "card-details">
					Email : &nbsp; {{i.email}}
				</div>
				{%endfor%}
		</div>
	</div>
	<div class="page-header" style="color:white;">
		<h2>
		Items posted by You :
		</h2>
	</div>
 	{% for i in obj %}
	<div class = "container">
			<div class = "item_temp">
				<img src = "{{ i.image.url }}" class = "item_image">
				<h1>{{i.item_name}}</h1>
				  <p class="title">Seller : {{i.username}}</p>
				  <p>Price : {{i.price}}</p>
				  <p>Description : {{i.description}}</p>
				  <a href="{% url 'BuyandSell:deleteme' i.item_name %}">
				  <button>Delete</button>
				  </a>					 
				
				  
			</div>
	</div>
	{%endfor%}

</body>

</html>

BuyandSell/templates/BuyandSell/sell_form.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Upload Project</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

<div class="container">
  <h2>Enter Project Details</h2>
  <form action="{% url 'BuyandSell:sell'%}" enctype="multipart/form-data" method="POST" >
    <div class="form-group">
    {%csrf_token%}
      <label for="name">Name:</label>
      <input type="text" class="form-control" id="id" placeholder="Enter Name of Project" name="name">
    </div>
    <div class="form-group">
      <label for="id">Group Leader's Roll:</label>
      <input type="text" class="form-control" id="id" placeholder="Enter Group Leader's Roll" name="id">
    </div>
    <div class="form-group">
      <label for="Guide">Guide:</label>
      <input type="text" class="form-control" id="price" placeholder="Enter Guide's name  Here" name="price">
    </div>
   
    <div class="form-group">
      <label for="description">Description:</label>
      <input type="text" class="form-control" id="description" placeholder="Write a brief description of Project " name="description">
    </div>
    <div class="form-group">
      <label for="image">Upload Poster:</label>
      <input type="file" name="image">
    </div>
     <div class="form-group">
      <label for="report">Upload Report:</label>
      <input type="file" name="report">
    </div>
    <div class="checkbox">
      <label><input type="checkbox" name="available"> Ready For Review</label>
    </div>
    <button type="submit" class="btn btn-default">Submit</button>
  </form>
</div>

</body>
</html>

BuyandSell/templates/BuyandSell/seller_info.html
<!DOCTYPE html>
<html>
<head>
	<title>User Details</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

	<!-- jQuery library -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

	<!-- Latest compiled JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
	<link rel="stylesheet" href="../../static/BuyandSell/style.css">
</head>
<body>
<div class = "my-container">
	<div class = "style_prevu_kit card-container">
			{% for i in obj %}
			<img src = "{{i.image.url}}" class ="card-img" />
			<div class = "card-details">
				Name : &nbsp; {{i.name}}
			</div>
			<div class = "card-details">
				Contact No. : &nbsp; {{i.contactno}}
			</div>
			<div class = "card-details">
				Email : &nbsp; {{i.email}}
			</div>
			{%endfor%}
	</div>
</div>
</body>
</html>

BuyandSell/templates/BuyandSell/signUp.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>SignUp for Project Hub</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

<div class="container">
  <h2>Enter Your Details</h2>
  <form action="{% url 'BuyandSell:signUp'%}" enctype="multipart/form-data" method="POST" >
    <div class="form-group">
        <label for="username">UserName</label>
        <input type="text"   name="username" >
    </div>
    <div class="form-group">
        <label for="password">Password</label>
        <input type="password"   name="password" >
    </div>


      <div class="form-group">
    {%csrf_token%}
      <label for="name">Name:</label>
      <input type="text" class="form-control" id="id" placeholder="Enter Name" name="name">
    </div>
    <div class="form-group">
        <label for="email">email</label>
        <input type="email"   name="email">
    </div>
     <div class="form-group">
        <label for="contactno">contactno</label>
        <input type="text"   name="contactno">
    </div>
    <div class="form-group">
      <label for="image">Upload Image:</label>
      <input type="file" name="image">
    </div>
    <button type="submit" class="btn btn-default">SignUp</button>
  </form>
</div>

</body>
</html>